name: "Update COVID19 config"
on:
  schedule:
    - cron:  '0 */3 * * *'
  push:
    branches:
      - master

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install asreview-statistics pandas lxml
      - name: Download and render config
        run: |
          python workflows/cord19_collect.py
          python workflows/covid19_preprints_collect.py
      - name: Commit files
        run: |
          git config --local user.email "asreview@uu.nl"
          git config --local user.name "Update bot"
          git add .
          git commit -m "Update config file"
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
